apiVersion: v1
kind: Service
metadata:
  labels:
    app: shop-commodity
    component: service
  name: shop-commodity
  namespace: ks-wssnail-shop
spec:
  ports:
    - name: http
      port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: shop-commodity
    component: service
    tier: backend
  sessionAffinity: None
