apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shop-order
    component: service
    tier: backend
  name: shop-order
  namespace: ks-wssnail-shop-dev
spec:
  progressDeadlineSeconds: 600
  replicas: REPLICAS
  selector:
    matchLabels:
      app: shop-order
      component: service
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: shop-order
        component: service
        tier: backend
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: shop-order
          image: REGISTRY/DOCKERHUB_NAMESPACE/APP_NAME:SNAPSHOT-BUILD_NUMBER
          livenessProbe:
            httpGet:
              path: /index
              port: 8091
            initialDelaySeconds: 90
            timeoutSeconds: 5
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /index
              port: 8091
            initialDelaySeconds: 90
            timeoutSeconds: 5
            failureThreshold: 5
            periodSeconds: 10
          imagePullPolicy: Always
          ports:
            - containerPort: 8091
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: app-yml
              mountPath: /snail/bootstrap.yml
              subPath: bootstrap.yml
      volumes:
        - name: app-yml
          configMap:
            name: shop-order-yml
            items:
            - key: bootstrap.yml
              path: bootstrap.yml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
