apiVersion: v1
kind: Service
metadata:
  labels:
    app: shop-order
    component: service
  name: shop-order
  namespace: ks-wssnail-shop-dev
spec:
  ports:
    - name: http
      port: 8091
      protocol: TCP
      targetPort: 8091
  selector:
    app: shop-order
    component: service
    tier: backend
  sessionAffinity: None
